/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unlam.asw.tp1;

import java.awt.event.KeyEvent;

/**
 *
 * @author Usuario
 */
public class VentanaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTriangulo
     */
    public VentanaTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLado1 = new javax.swing.JLabel();
        jTextFieldLado1 = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLado2 = new javax.swing.JLabel();
        jTextFieldLado2 = new javax.swing.JTextField();
        jLabelLado3 = new javax.swing.JLabel();
        jTextFieldLado3 = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo de triángulos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLado1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLado1.setText("Lado 1");
        getContentPane().add(jLabelLado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 71, -1, 29));

        jTextFieldLado1.setTransferHandler(null);
        jTextFieldLado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLado1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldLado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, 72, -1));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Tipo de triángulos");
        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 20, 190, -1));

        jLabelLado2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLado2.setText("Lado 2");
        getContentPane().add(jLabelLado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 75, -1, -1));

        jTextFieldLado2.setTransferHandler(null);
        jTextFieldLado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLado2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldLado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 75, 72, -1));

        jLabelLado3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLado3.setText("Lado 3");
        getContentPane().add(jLabelLado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 75, -1, -1));

        jTextFieldLado3.setTransferHandler(null);
        jTextFieldLado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLado3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldLado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 75, 72, -1));

        jButtonCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCalcular.setText("CALCULAR");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 119, 144, 49));

        jLabelResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultado.setToolTipText("");
        getContentPane().add(jLabelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 174, 590, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        try {
            if (jTextFieldLado1.getText().contains(".") || jTextFieldLado1.getText().contains(",")
                    || jTextFieldLado2.getText().contains(".") || jTextFieldLado2.getText().contains(",")
                    || jTextFieldLado3.getText().contains(".") || jTextFieldLado3.getText().contains(",")) {
                jLabelResultado.setText("Solo se admiten números enteros.");
            } else {
                Triangulo triangulo = new Triangulo(
                        Integer.parseInt(jTextFieldLado1.getText()),
                        Integer.parseInt(jTextFieldLado2.getText()),
                        Integer.parseInt(jTextFieldLado3.getText())
                );

                switch (triangulo.obtenerTipoTriangulo()) {
                    case Triangulo.EQUILATERO:
                        jLabelResultado.setText("Triángulo equilátero");
                        break;
                    case Triangulo.ESCALENO:
                        jLabelResultado.setText("Triángulo escaleno");
                        break;
                    case Triangulo.ISOSCELES:
                        jLabelResultado.setText("Triángulo isósceles");
                        break;
                    case Triangulo.NO_ES_TRIANGULO:
                        jLabelResultado.setText("No se puede construir un Triángulo con los lados ingresados");
                        break;
                    default:
                        jLabelResultado.setText("Todos los valores deben ser mayores a cero");
                        break;
                }
            }
        } catch (NumberFormatException ex) {
            jLabelResultado.setText("Ingrese tres valores numéricos");
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldLado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLado1KeyTyped
        if (jTextFieldLado1.getText().length() >= 6
                && !(evt.getKeyChar() == KeyEvent.VK_DELETE
                || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLado1KeyTyped

    private void jTextFieldLado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLado2KeyTyped
        if (jTextFieldLado2.getText().length() >= 6
                && !(evt.getKeyChar() == KeyEvent.VK_DELETE
                || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLado2KeyTyped

    private void jTextFieldLado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLado3KeyTyped
        if (jTextFieldLado3.getText().length() >= 6
                && !(evt.getKeyChar() == KeyEvent.VK_DELETE
                || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldLado3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabelLado1;
    private javax.swing.JLabel jLabelLado2;
    private javax.swing.JLabel jLabelLado3;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldLado1;
    private javax.swing.JTextField jTextFieldLado2;
    private javax.swing.JTextField jTextFieldLado3;
    // End of variables declaration//GEN-END:variables
}
